#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Git 分支管理模块

管理 Git 分支的创建、提交、合并、回滚
"""

import subprocess


class GitManager:
    """Git 管理器"""

    def __init__(self, config):
        self.config = config

    def create_branch(self, branch_name):
        """创建新分支"""
        result = subprocess.run(
            ["git", "checkout", "-b", branch_name],
            capture_output=True,
            text=True
        )

        return result.returncode == 0

    def commit(self, category, message):
        """
        提交修复

        Args:
            category: 问题类别 (config/database/api/frontend)
            message: 提交消息
        """
        commit_msg = f"""fix({category}): {message}

🤖 Auto-generated by Auto-Fix System
Co-Authored-By: Claude Sonnet 4.5 <noreply@anthropic.com>
"""

        # 添加所有更改
        subprocess.run(["git", "add", "."], capture_output=True)

        # 提交
        result = subprocess.run(
            ["git", "commit", "-m", commit_msg],
            capture_output=True,
            text=True
        )

        return result.returncode == 0

    def merge_to_main(self, branch_name):
        """合并分支到主分支"""
        # 切换到主分支
        subprocess.run(["git", "checkout", "main"], capture_output=True)

        # 合并
        result = subprocess.run(
            ["git", "merge", branch_name],
            capture_output=True,
            text=True
        )

        return result.returncode == 0

    def delete_branch(self, branch_name):
        """删除分支"""
        result = subprocess.run(
            ["git", "branch", "-d", branch_name],
            capture_output=True,
            text=True
        )

        return result.returncode == 0

    def rollback_last_commit(self):
        """回滚最后一次提交"""
        result = subprocess.run(
            ["git", "reset", "--hard", "HEAD~1"],
            capture_output=True,
            text=True
        )

        return result.returncode == 0

    def get_current_branch(self):
        """获取当前分支名"""
        result = subprocess.run(
            ["git", "rev-parse", "--abbrev-ref", "HEAD"],
            capture_output=True,
            text=True
        )

        if result.returncode == 0:
            return result.stdout.strip()
        return None
